# Generated by Django 2.0 on 2020-04-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='姓名', max_length=15, verbose_name='姓名')),
                ('tempture', models.DecimalField(decimal_places=1, help_text='温度', max_digits=3, verbose_name='温度')),
                ('address', models.CharField(help_text='地址', max_length=60, verbose_name='地址')),
                ('date', models.DateField(help_text='时间', verbose_name='时间')),
                ('age', models.IntegerField(help_text='年龄', verbose_name='年龄')),
            ],
        ),
    ]
